name = "key-system"
main = "worker.js"
compatibility_date = "2026-09-29"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "vrilz-key-db"
database_id = "1f12915e-806c-4ad6-adad-3b73d111804d"
